### ISSUE TITLE
Server crashed today

### ISSUE THREAD

**Issue by Mubelotix** [Mubelotix/stotra#5]
```
Dec 23 11:41:14 nuc docker[3894141]: stotra-backend  | TypeError: Cannot destructure property 'symbol' of 'quote' as it is undefined.
Dec 23 11:41:14 nuc docker[3894141]: stotra-backend  |     at /usr/src/app/dist/src/utils/requests.js:37:17
Dec 23 11:41:14 nuc docker[3894141]: stotra-backend  |     at Generator.next (<anonymous>)
Dec 23 11:41:14 nuc docker[3894141]: stotra-backend  |     at fulfilled (/usr/src/app/dist/src/utils/requests.js:5:58)
Dec 23 11:41:14 nuc docker[3894141]: stotra-backend  |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
Dec 23 11:41:14 nuc docker[3894141]: stotra-backend  | Error fetching HUWWF stock data: TypeError: Cannot destructure property 'symbol' of 'quote' as it is undefined.
Dec 23 11:41:14 nuc docker[3894141]: stotra-backend  |     at /usr/src/app/dist/src/utils/requests.js:37:17
Dec 23 11:41:14 nuc docker[3894141]: stotra-backend  |     at Generator.next (<anonymous>)
Dec 23 11:41:14 nuc docker[3894141]: stotra-backend  |     at fulfilled (/usr/src/app/dist/src/utils/requests.js:5:58)
Dec 23 11:41:14 nuc docker[3894141]: stotra-backend  |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
Dec 23 11:41:14 nuc docker[3894141]: stotra-backend  | /usr/src/app/dist/src/utils/requests.js:74
Dec 23 11:41:14 nuc docker[3894141]: stotra-backend  |             throw new Error(err);
Dec 23 11:41:14 nuc docker[3894141]: stotra-backend  |                   ^
Dec 23 11:41:14 nuc docker[3894141]: stotra-backend  |
Dec 23 11:41:14 nuc docker[3894141]: stotra-backend  | Error: TypeError: Cannot destructure property 'symbol' of 'quote' as it is undefined.
Dec 23 11:41:14 nuc docker[3894141]: stotra-backend  |     at /usr/src/app/dist/src/utils/requests.js:74:19
Dec 23 11:41:14 nuc docker[3894141]: stotra-backend  |     at Generator.next (<anonymous>)
Dec 23 11:41:14 nuc docker[3894141]: stotra-backend  |     at fulfilled (/usr/src/app/dist/src/utils/requests.js:5:58)
Dec 23 11:41:14 nuc docker[3894141]: stotra-backend  |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

**Comment by Mubelotix** [comment]
Fixed in https://github.com/Mubelotix/stotra/commit/8d8e94945ad593f2af8f343ba86b7651fb13adff
